//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MensajesEntities : DbContext
    {
        public MensajesEntities()
            : base("name=MensajesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mensaje> Mensaje { get; set; }
        public virtual DbSet<Tipo> Tipo { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<Usuario> SpEliminarUsuario(string nombreLogueo)
        {
            var nombreLogueoParameter = nombreLogueo != null ?
                new ObjectParameter("NombreLogueo", nombreLogueo) :
                new ObjectParameter("NombreLogueo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usuario>("SpEliminarUsuario", nombreLogueoParameter);
        }
    
        public virtual ObjectResult<Usuario> SpEliminarUsuario(string nombreLogueo, MergeOption mergeOption)
        {
            var nombreLogueoParameter = nombreLogueo != null ?
                new ObjectParameter("NombreLogueo", nombreLogueo) :
                new ObjectParameter("NombreLogueo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usuario>("SpEliminarUsuario", mergeOption, nombreLogueoParameter);
        }
    }
}
